routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => "admin"], function() {

    Route::resource('Ext_Images', 'Controller_Ext_Images');

    Route::get('Ext_Images/{id}/destroy', [
        'uses' => 'Controller_Ext_Images@destroy',
        'as' => 'Ext_Images.destroyId'
    ]);

    Route::resource('Categories_Images', 'Controller_Categories_Images');

    Route::get('Categories_Images/{id}/destroy', [
        'uses' => 'Controller_Categories_Images@destroy',
        'as' => 'Categories_Images.destroyId'
    ]);

    Route::resource('Categories', 'Controller_Categories');

    Route::get('Categories/{id}/destroy', [
        'uses' => 'Controller_Categories@destroy',
        'as' => 'Categories.destroyId'
    ]);

    Route::resource('Product_Status', 'Controller_Product_Status');

    Route::get('Product_Status/{id}/destroy', [
        'uses' => 'Controller_Product_Status@destroy',
        'as' => 'Product_Status.destroyId'
    ]);

    Route::resource('Stars', 'Controller_Stars');
    
    Route::get('Stars/{id}/destroy', [
        'uses' => 'Controller_Stars@destroy',
        'as' => 'Stars.destroyId'
    ]);
});

Route::group(['prefix' => "Images"], function() {

    Route::resource('Images', 'Controller_Images');
});

Route::group(['prefix' => "Products"], function() {

    Route::resource('Products', 'Controller_Products');
});

Route::group(['prefix' => "Answer_Questions"], function() {

    Route::resource('Answer_Questions', 'Controller_Answer_Questions');
});

Route::group(['prefix' => "Buyers"], function() {

    Route::resource('Buyers', 'Controller_Buyers');
});

Route::group(['prefix' => "Question_Posts"], function() {

    Route::resource('Question_Posts', 'Controller_Question_Posts');
});

Route::group(['prefix' => "Posts"], function() {

    Route::resource('Posts', 'Controller_Posts');
});

Route::group(['prefix' => "Product_Reviews"], function() {

    Route::resource('Product_Reviews', 'Controller_Product_Reviews');
});

Route::group(['prefix' => "Purchases"], function() {

    Route::resource('Purchases', 'Controller_Purchases');
});

Route::group(['prefix' => "Seller_Reviews"], function() {

    Route::resource('Seller_Reviews', 'Controller_Seller_Reviews');
});

Route::group(['prefix' => "Sellers"], function() {

    Route::resource('Sellers', 'Controller_Sellers');
});

Route::group(['prefix' => "Users"], function() {

    Route::resource('Users', 'Controller_Users');
});

app/Ext_Images.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ext_Images extends Model {

    protected $table = 'ext_images';
    protected $fillable = ['id','name','description','status'];

    public function image() {
        return $this->belongsTo('App\Image');
    }

}

resources/views/admin/ext_Images/create.blade.php
@extends('admin.template.main')

@section('title')

Crear una Extension para Imagenes

@stop


@section('nav')

@extends('admin.template.nav')

@stop

@section('mainContainer')

{!! Form::open(['route' => 'Ext_Images.store']) !!}

<div class="row">
    <h2>Extensiones de imagenes</h2>

</div>

<div class="form-group">
    {!!  Form::label('name', 'Nombre'); !!}
    {!!  Form::text('name' , null,['class' => 'form-control' , 'placeholder' => 'JPG']); !!}

</div>
<div class="form-group">
    {!!  Form::label('description', 'Descripcion'); !!}
    {!!  Form::text('description' , null,['class' => 'form-control' , 'placeholder' => 'Imagenes']); !!}

</div>
<div class="form-group">

    {!! Form::submit('Guardar!' , ['class' => 'form-control btn btn-success'  ]); !!}
</div>
{!! Form::close()!!}

@stop

@section('footer')



@stop

resources/views/admin/ext_Images/edit.blade.php
@extends('admin.template.main')

@section('title')

Crear una Extension para Imagenes

@stop


@section('nav')

@extends('admin.template.nav')

@stop

@section('mainContainer')


<div class="row">
    <h2>Extensiones de imagenes</h2>

</div>

{!! Form::open(['route' => ['Ext_Images.update' , $extension->id] , 'method' =>'put']) !!}


<div class="form-group">
    {!!  Form::label('name', 'Nombre'); !!}
    {!!  Form::text('name' , $extension->name ,['class' => 'form-control' , 'placeholder' => 'JPG']); !!}

</div>
<div class="form-group">
    {!!  Form::label('description', 'Descripcion'); !!}
    {!!  Form::text('description' , $extension->description ,['class' => 'form-control' , 'placeholder' => 'Imagenes']); !!}

</div>
<div class="form-group">

    {!! Form::submit('Guardar!' , ['class' => 'form-control btn btn-success'  ]); !!}
</div>
{!! Form::close()!!}

@stop

@section('footer')



@stop

resources/views/admin/ext_Images/index.blade.php
@extends('admin.template.main')
@section('title')
Mostrar las extensiones guarda
@stop
@section('nav')
@extends('admin.template.nav')
@stop

@section('mainContainer')
<div class="row">
    <h2>Extensiones de imagenes</h2>

</div>

<div class="row">
    <div class="col-md-1 offset-md-11"><a class="btn btn-success" href="{{route('Ext_Images.create')}}">+</a></div>
    
    
</div>
<table class="table">
    <thead>
    <th>Id</th>
    <th>Name</th>
    <th>Descripcion</th>
    <th>Actions</th>
</thead>
<tbody>
    @foreach($allExtensions as $ext)
    <tr>
        <td>{{ $ext->id }} </td>
        <td>{{ $ext->name }} </td>
        <td>{{ $ext->description }} </td>
        <td>
            <a href="{{ route('Ext_Images.destroyId', $ext->id)}}" class="btn btn-danger ">
                <span class="glyphicon glyphicon-search" aria-hidden="true">X</span>
            </a>
            <a href="{{ route('Ext_Images.edit', $ext->id) }}" class="btn btn-warning">
                 <span class="glyphicon glyphicon-search" aria-hidden="true">U</span>
            </a>
        </td>
    </tr>
    @endforeach
</tbody>

</table>



@stop